pull_request_rules:
  - name: Automatic merge on PullApprove
    conditions:
      - or:
        - "check-success=pullapprove"
        - label="fast track"
        - label="automated pr"
      - "#approved-reviews-by>=1"
      - "#review-threads-unresolved=0"
      - "-draft"
      - "#check-failure=0"               # Don't auto merge with a failure
      - "#check-pending=0"               # Don't auto merge with anything pending
      - or:
        - "check-success=pullapprove"
        - "check-skipped=pullapprove"
        - "check-neutral=pullapprove"
    actions:
      merge:
        method: squash
