# This Workflow is handling the automated approval of PRs that are tagged with specific
# label "automated pr" and is used to handle automatic releases
name: Auto approve

on:
  pull_request:
    types: [labeled]

jobs:
  auto-approve:
    if: |
      github.actor == 'Automator77' &&
      github.event.label.name == 'automated pr' &&
      github.repository == 'project-chip/matter.js'  
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
