on:
  schedule:
    - cron: 0 2 * * * # Every day at 02:00
  workflow_dispatch: # Manually on demand
  push:
    branches:
      - chiptests

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CONNECTEDHOMEIP_TAG: "master" # v1.1.0.1 do not work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Debian deps
        id: install_deps
        run: |
          sudo apt-get update
          sudo apt-get install git gcc g++ pkg-config libssl-dev libdbus-1-dev libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev python3-pip unzip libgirepository1.0-dev libcairo2-dev libreadline-dev
      - name: Prepare Bin Directory
        id: prepare_bin
        run: |
          mkdir bin

      - name: Cache Bin files
        id: cache_bin
        uses: actions/cache@v3
        env:
          cache-name: chip-bin
        with:
          path: ./bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.CONNECTEDHOMEIP_TAG }}
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }}
        name: Get Chip Repo
        id: connectedhomeip
        run: |
          git clone https://github.com/project-chip/connectedhomeip.git --depth=1 --branch=$CONNECTEDHOMEIP_TAG
          cd connectedhomeip
          scripts/checkout_submodules.py --shallow --platform linux
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }}
        name: Build Chiptool
        id: build_chiptool
        run: |
          cd connectedhomeip
          source scripts/activate.sh
          gn gen out/debug
          ninja -C out/debug chip-tool
          ls -ls ./out/debug/
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }}
        name: Build examples
        id: build_examples
        run: |
          cd connectedhomeip
          source scripts/activate.sh
          ./scripts/build/build_examples.py --target linux-x64-tests build
          ls -la ./out/
          ls -la ./out/linux-x64-tests/
          ls -la ./out/linux-x64-tests/examples/
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }}
        name: Copy files
        id: copy_files
        run: |
          cp connectedhomeip/out/debug/chip-tool bin/
          cp connectedhomeip/out/linux-x64-tests/examples/* bin/
      - name: test execution
        id: test_execution
        run: |
          cd bin
          ./chip-tool
          ./chip-tool pairing onnetwork
