on:
  schedule:
    - cron: 0 2 * * * # Every day at 02:00
  workflow_dispatch: # Manually on demand
  push:
    branches:
      - chiptests

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CONNECTEDHOMEIP_TAG: "master" # v1.1.0.1 do not work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Debian deps
        id: install_deps
        run: |
          sudo apt-get update
          sudo apt-get install git gcc g++ pkg-config libssl-dev libdbus-1-dev libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev python3-pip unzip libgirepository1.0-dev libcairo2-dev libreadline-dev
      - name: Prepare Bin Directory
        id: prepare_bin
        run: |
          mkdir bin

      - name: Cache Bin files
        id: cache_bin
        uses: actions/cache@v3
        env:
          cache-name: chip-bin
        with:
          path: ./bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.CONNECTEDHOMEIP_TAG }}
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }}
        name: Get Chip Repo
        id: connectedhomeip
        run: |
          git clone https://github.com/project-chip/connectedhomeip.git --depth=1 --branch=$CONNECTEDHOMEIP_TAG
          cd connectedhomeip
          scripts/checkout_submodules.py --shallow --platform linux
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }} || contains(github.event.head_commit.message, '[rebuild-chip]') == true
        name: Build executables
        id: build_executables
        run: |
          cd connectedhomeip
          source scripts/activate.sh
          ./scripts/build/build_examples.py --target linux-x64-all-clusters 
          cp connectedhomeip/out/linux-x64-all-clusters/chip-all-clusters-app bin/
          rm -rf connectedhomeip/out/linux-x64-all-clusters
          ./scripts/build/build_examples.py --target linux-x64-all-clusters-minimal
          cp connectedhomeip/out/linux-x64-all-clusters-minimal/chip-all-clusters-minimal-app bin/
          rm -rf connectedhomeip/out/linux-x64-all-clusters-minimal
          ./scripts/build/build_examples.py --target linux-x64-thermostat
          cp connectedhomeip/out/linux-x64-thermostat/thermostat-app bin/
          rm -rf connectedhomeip/out/linux-x64-thermostat
          ./scripts/build/build_examples.py --target linux-x64-light
          cp connectedhomeip/out/linux-x64-light/chip-lighting-app bin/
          rm -rf connectedhomeip/out/linux-x64-light
          ./scripts/build/build_examples.py --target linux-x64-lock
          cp connectedhomeip/out/linux-x64-lock/chip-lock-app bin/
          rm -rf connectedhomeip/out/linux-x64-lock
          ./scripts/build/build_examples.py --target linux-x64-shell
          cp connectedhomeip/out/linux-x64-shell/chip-shell bin/
          rm -rf connectedhomeip/out/linux-x64-shell
          ./scripts/build/build_examples.py --target linux-x64-ota-provider
          cp connectedhomeip/out/linux-x64-ota-provider/chip-ota-provider-app bin/
          rm -rf connectedhomeip/out/linux-x64-ota-provider
          ./scripts/build/build_examples.py --target linux-x64-ota-requestor
          cp connectedhomeip/out/linux-x64-ota-requestor/chip-ota-requestor-app bin/
          rm -rf connectedhomeip/out/linux-x64-ota-requestor
          ./scripts/build/build_examples.py --target linux-x64-tv-app
          cp connectedhomeip/out/linux-x64-tv-app/chip-tv-app bin/
          rm -rf connectedhomeip/out/linux-x64-tv-app
          ./scripts/build/build_examples.py --target linux-x64-tv-casting-app  
          cp connectedhomeip/out/linux-x64-tv-casting-app/chip-tv-casting-app bin/
          rm -rf connectedhomeip/out/linux-x64-tv-casting-app
          ./scripts/build/build_examples.py --target linux-x64-bridge
          cp connectedhomeip/out/linux-x64-bridge/chip-bridge-app bin/
          rm -rf connectedhomeip/out/linux-x64-bridge
          ./scripts/build/build_examples.py --target linux-x64-contact-sensor
          cp connectedhomeip/out/linux-x64-contact-sensor/contact-sensor-app bin/
          rm -rf connectedhomeip/out/linux-x64-contact-sensor
          ./scripts/build/build_examples.py --target linux-x64-dishwasher
          cp connectedhomeip/out/linux-x64-dishwasher/chip-dishwasher-app bin/
          rm -rf connectedhomeip/out/linux-x64-dishwasher
          ./scripts/build/build_examples.py --target linux-x64-chip-cert
          cp connectedhomeip/out/linux-x64-chip-cert/chip-cert bin/
          rm -rf connectedhomeip/out/linux-x64-chip-cert
          ./scripts/build/build_examples.py --target linux-x64-simulated-app1
          cp connectedhomeip/out/linux-x64-simulated-app1/chip-app1 bin/
          rm -rf connectedhomeip/out/linux-x64-simulated-app1
          ./scripts/build/build_examples.py --target linux-x64-simulated-app2
          cp connectedhomeip/out/linux-x64-simulated-app2/chip-app2 bin/
          rm -rf connectedhomeip/out/linux-x64-simulated-app2
          ./scripts/build/build_examples.py --target linux-x64-chip-tool build
          cp connectedhomeip/out/linux--x64-chip-tool/chip-tool bin/
      - if: ${{ steps.cache-bin.outputs.cache-hit != 'true' }} || contains(github.event.head_commit.message, '[rebuild-chip]') == true
        name: Cleanup
        id: cleanup
        run: |
          rm -rf connectedhomeip
      - name: test execution
        id: test_execution
        run: |
          cd bin
          ./chip-tool
          ./chip-tool pairing onnetwork
