# This workflow executed the chip tool tests against matter.js
name: Chip Tool tests

on:
  schedule:
    - cron: 0 2 * * * # Every day at 02:00
  workflow_dispatch: # Manually on demand
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}-chip-tool-tests
  cancel-in-progress: true

jobs:
  chip-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out matter.js
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - "chip-testing/**"
              - "packages/matter.js/src/cluster/**"
              - "packages/matter.js/src/tlv/**"
              - ".github/workflows/chip-tool-tests.yml"

      - uses: dorny/paths-filter@v2
        id: changes-long-tests
        with:
          filters: |
            src:
              - "chip-testing/src/suites-long/**"

      - if: ${{ github.event_name == 'schedule' || ((github.event_name == 'push' || github.event_name == 'pull_request') && steps.changes.outputs.src == 'true') || github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[execute-chiptests]') == true }}
        name: Chip Tool tests required to run?
        run: echo "CHIP_TESTS_REQUIRED=1" >> $GITHUB_ENV

      - if: ${{ contains(github.event.head_commit.message, '[rebuild-chip]') == true }}
        name: Chip Tool rebuild required?
        run: |
          echo "CHIP_TESTS_REQUIRED=1" >> $GITHUB_ENV
          echo "REBUILD_CHIP=1" >> $GITHUB_ENV

      - name: Get day of the week (to consider if long tests should run)
        run: |
          echo "DOW=$(date +%u)" >> $GITHUB_ENV

      - name: Prepare and execute chip tests
        if: ${{ env.CHIP_TESTS_REQUIRED == 1 }}
        uses: ./.github/actions/prepare-chip-testing
        with:
          rebuild-chip-tool: ${{ env.REBUILD_CHIP }}

      # Execute normal tests
      - name: test execution
        id: test-execution
        shell: bash
        run: |
          cd chip-testing
          npm run test-chip

      # Execute long tests
      - if: ${{ (env.DOW == 6 && github.event_name == 'schedule') || steps.changes-long-tests.outputs.src == 'true' }}
        name: Enable Long tests if needed
        id: test-execution-long
        shell: bash
        run: |
          cd chip-testing
          LONG_TESTS_ONLY=1 npm run test-chip
