# This workflow executed the chip tool tests against matter.js
name: Matter.js Controller vs Chip Device Tests

on:
  schedule:
    - cron: 0 4 * * * # Every day at 04:00 (chip-tool-test should have finished by then and rebuild is done)
  workflow_dispatch: # Manually on demand
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: ${{ github.ref }}-chip-matterjs-tests
  cancel-in-progress: true

jobs:
  # If we need to do anything make sure that chip binaries are build and environment can be set up
  prepare-chip-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out matter.js
        uses: actions/checkout@v4

      - name: Prepare chip tests and rebuild chip-tool if needed
        uses: ./.github/actions/prepare-chip-testing
        with:
          rebuild-chip-tool: "false"
          build-matter-js: "false"

  matterjs-all-chip-apps:
    needs: [prepare-chip-build]
    runs-on: ubuntu-latest

    steps:
      - name: Check out matter.js
        uses: actions/checkout@v4

      - name: Initialize chip tests
        uses: ./.github/actions/prepare-chip-testing
        with:
          rebuild-chip-tool: 'false'

      - name: Patch Test runner interface-id
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require("fs");
            let file= fs.readFileSync("./connectedhomeip/scripts/tests/chiptest/linux.py", "utf8");
            // Patch the test runner to execute controlelr and app on same network interface
            file = file.replaceAll("'ip netns exec tool'", "'ip netns exec app'");
            fs.writeFileSync("./connectedhomeip/scripts/tests/chiptest/linux.py", file);

      - name: Chip-Apps execution with matter.js controller
        id: test-execution-matterjs-chip
        shell: bash
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
          sudo sysctl -w net.ipv4.conf.all.forwarding=1
          sudo sysctl -w net.ipv6.conf.all.forwarding=1
          cd connectedhomeip
          ./scripts/run_in_build_env.sh  \
            './scripts/tests/run_test_suite.py \
              --runner chip_tool_python \
              --chip-tool ../chip-testing/dist/esm/ControllerWebSocketTestApp.js \
              --log-level info \
              --target-glob "{Test_*,}" \
              --target-skip-glob "{Test_TC_ACE_1_6,Test_TC_BDX_*,Test_TC_DEMM_2_1,Test_TC_DGTHREAD*,Test_TC_DGWIFI*,Test_TC_DRLK_2_7,Test_TC_DRLK_2_8,Test_TC_EEVSEM_2_1,Test_TC_LVL_9_1,Test_TC_LWM_2_1,Test_TC_OO_2_7,Test_TC_SC_5_2,Test_TC_S_2_2,Test_TC_S_2_3,Test_TC_S_2_4,Test_TC_WIFINM_2_1}" \
              run \
              --all-clusters-app ../bin/chip-all-clusters-app \
              --lock-app ../bin/chip-lock-app \
              --bridge-app ../bin/chip-bridge-app \
              --tv-app ../bin/chip-tv-app \
              --lit-icd-app ../bin/lit-icd-app \
              --microwave-oven-app ../bin/chip-microwave-oven-app \
              --rvc-app ../bin/chip-rvc-app \
              --network-manager-app ../bin/matter-network-manager-app \
            '
